### ISSUE TITLE
Database migrations not working

### ISSUE THREAD

**Issue by hkockerbeck** [corex/kanboard-crproject#2]
When the plugin is updated, changes in the database schema aren't applied. That's because your database migrations don't have the structure Kanboard expects them to have. `Schema/Mysql.php` is supposed to look something like this:

    // ...
    const VERSION = 3;
    // ...
    function version_1($pdo)
    {
    // the initial schema, version 1
    }

    function version_2($pdo)
    {
    // changes from version 1 to version 2
    }

    function version_3($pdo)
    {
    // changes from version 2 to version 3
    }

When you need to change the db schema again for a later version of the plugin, you change `VERSION` to 4 and add a function `version_4` that applies the changes, and so on. See the [Kanboard docs](https://docs.kanboard.org/en/latest/plugins/schema_migrations.html) for reference.

I haven't looked into it, but I'd assume the same principle applies to the other schemas (Postgres and SQLite) as well.

**Comment by corex** [comment]
O.O I was not aware that anyone used this plugin. I will look into the codebase as soon as possible. Thanks for reporting it.

**Comment by corex** [comment]
This should be fixed now. 1.2.1 released.
