### ISSUE TITLE
Plugin still announces itself as version 1.0.0 in version 1.2.0

### ISSUE THREAD

**Issue by hkockerbeck** [corex/kanboard-crproject#3]
If you update the version number of the plugin, you may want to update `getPluginVersion()` in `Plugin.php` accordingly, so the plugin announces its version correctly.

**Comment by corex** [comment]
O.O I was not aware that anyone used this plugin. I will look into the codebase as soon as possible. Thanks for reporting it.

**Comment by corex** [comment]
This should be fixed now. 1.2.1 released.
